---
train_config:
  # random seed
  seed: 3
  # experiment name, for logging purposes
  exp_name: 'th+mpg-optimal-3'
  # learning rate
  lr_rate: 0.0003
  # Adam weight decay
  w_decay: 0
  # total training episodes
  n_episode: 1000
  # training batch size from replay
  batch_size: 256
  # number of environment steps per policy update
  update_step: 10
  # whether to use MSE loss for the Q function. If set to false, a huber loss
  # is used instead.
  mse_loss: false
  # number of episodes between saving and logging intervals
  save_every: 5
  # number of training iterations to perform on initial demonstrations
  pretrain_step: 0

agent_config:
  # standard deviation for noise from the output of the target actor policy
  policy_noise: 0.2
  # clipping term for the noise injected in the target actor policy
  noise_clip: 0.5
  # number of training steps per actor policy update step. The critic policy is
  # updated every training step
  policy_freq: 2
  # reward discount
  gamma: 0.99
  # number of samples in the replay buffer
  replay_buffer_size: 500000
  # continuous update, source network portion, per actor update step
  tau: 0.005
  # standard deviation for Gaussian action noise
  action_noise_std: 0.1
  # whether to update priorities in prioritized experience replay
  no_per: true
  const_demo_priority: 0.99 # Should be less than 1
  const_min_priority: 0.001
  # path to the initial policy. If set to a value other than "", the initial
  # policy from this path/epoch is loaded at the start of training.
  pretrain_path: ""  # "result/th/3/"
  # the epoch to use whether loading a policy from pretrain_path
  pretrain_epoch: 40
  # the weighting term for the Elastic Weight Consolidation penalty
  ewc_lambda: 0
  # the weighting term for the imitation penalty
  il_lambda: 0

demo_config:
  # whether to load demonstration data
  load_demo_data: true
  # folder containing demonstration pkl files
  demo_dir: './demo/optimal/th+mpg'
  # whether demonstrations were collected from a random action distribution. In
  # this case, demos are not stored permanently
  random: false

env_config:
  # minimum desirable space headway. If set to -1, no penalty is applied.
  h_min: -1
  # maximum desirable space headway. If set to -1, no penalty is applied.
  h_max: 100
  # minimum desirable time headway. If set to -1, no penalty is applied.
  th_min: 1.0
  # maximum desirable time headway. If set to -1, no penalty is applied.
  th_max: -1
  # whether to use the energy reward
  use_energy: true
  # number of timesteps to average the energy reward across
  energy_steps: 5
